"use client";

import { useState } from "react";
import {
  BookOpen,
  LayoutDashboard,
  Bot,
  Sparkles,
  Search,
  FileText,
  Shield,
  Settings,
  ChevronRight,
  CheckCircle2,
  AlertTriangle,
  ArrowRight,
  Zap,
  Wallet,
  Eye,
  Rocket,
} from "lucide-react";
import { cn } from "@/lib/utils";

interface Step {
  number: number;
  title: string;
  description: string;
  details: string[];
  tips?: string[];
  warnings?: string[];
  page?: string;
}

const gettingStartedSteps: Step[] = [
  {
    number: 1,
    title: "Set Up Your Wallet",
    description: "Connect your Hyperliquid wallet to start trading",
    details: [
      "Go to app.hyperliquid.xyz and connect your wallet (MetaMask or any EVM wallet)",
      "Fund your wallet with ETH for trading capital",
      "Go to Settings page in this dashboard and make sure Paper Mode is ON for testing",
      "When ready for live trading, switch to Live Mode and enter your wallet private key in the bot .env file",
    ],
    tips: [
      "Always start with Paper Mode to test your strategies with virtual funds before using real money",
      "Never share your private key with anyone. It is stored locally in your .env file only",
    ],
    warnings: [
      "Live Mode uses REAL funds. Double-check all settings before switching from Paper to Live",
    ],
    page: "settings",
  },
  {
    number: 2,
    title: "Understand the Overview",
    description: "Your main dashboard showing real-time bot activity",
    details: [
      "Portfolio Value: Shows your total equity in ETH",
      "Equity Chart: Tracks your account value over time vs benchmark",
      "Live Signals: Real-time buy/sell signals generated by your strategies",
      "Active Positions: Currently open trades with unrealized P&L",
      "Active Strategies: Quick status of all 4 trading strategies",
      "Signal confidence percentage tells you how strong the signal is (higher = better)",
      "Green signals are BUY, red signals are SELL, amber signals are CLOSE",
    ],
    tips: [
      "Keep the Overview page open while trading to monitor signals in real-time",
      "Signals auto-refresh. New signals appear at the top with a confidence score",
    ],
    page: "overview",
  },
  {
    number: 3,
    title: "Configure Strategies",
    description: "Enable and fine-tune your 4 trading strategies",
    details: [
      "StochRSI + Supertrend: Combines Stochastic RSI for overbought/oversold with Supertrend for trend direction. Good for catching reversals in trending markets",
      "MACD + BB + RSI: Triple confirmation using MACD crossovers within Bollinger Bands with RSI divergence. Higher confidence, fewer signals",
      "BB Winner PRO: Mean reversion strategy trading Bollinger Band touches and squeezes with volume confirmation. Excels in ranging/sideways markets",
      "Supertrend + RSI: Trend-following using Supertrend for direction and RSI for timing entry. Adaptive position sizing based on ATR",
      "Each strategy has adjustable parameters (RSI periods, BB settings, stop loss, take profit, etc.)",
      "Click the toggle switch to enable/disable each strategy independently",
    ],
    tips: [
      "Start with 1-2 strategies enabled rather than all 4. This reduces risk and makes it easier to evaluate performance",
      "MACD+BB+RSI has the highest win rate but fewest trades. Good for patient traders",
      "BB Winner PRO works best in sideways markets. Disable it during strong trends",
      "Default parameters are already optimized, but you can fine-tune them using the AI Optimizer",
    ],
    warnings: [
      "Changing strategy parameters while trades are open may affect position management",
    ],
    page: "strategies",
  },
  {
    number: 4,
    title: "Use the AI Optimizer",
    description: "Let Optuna find the best parameters automatically",
    details: [
      "The AI Optimizer uses Bayesian optimization (Optuna TPE) to find the best strategy parameters",
      "It runs backtests on historical data to evaluate thousands of parameter combinations",
      "Parameter Importance chart shows which parameters matter most for performance",
      "Best Sharpe Ratio indicates risk-adjusted returns (higher is better)",
      "Improvement % shows how much the optimized parameters outperform defaults",
      "Select a strategy, set the number of optimization iterations, and click Start Optimization",
      "Results show the best parameters found, which you can then apply in the Strategies page",
    ],
    tips: [
      "Run optimization with at least 500 iterations for reliable results",
      "Optimize one strategy at a time for best results",
      "Re-run optimization periodically (weekly) as market conditions change",
      "The optimizer uses GMM clustering for market regime detection, so it adapts to different market conditions",
    ],
    warnings: [
      "Optimization uses historical data. Past performance does not guarantee future results",
      "Over-optimizing (too many iterations) can lead to overfitting. Stick to 500-1000 iterations",
    ],
    page: "ai-optimizer",
  },
  {
    number: 5,
    title: "Screen Trading Pairs",
    description: "Find the best trading pairs based on trend and risk scores",
    details: [
      "The Pair Screener shows all available ETH trading pairs with key metrics",
      "Trend Score (0-100): Higher means stronger trend. Look for scores above 70",
      "Risk Score (0-100): Lower is safer. Avoid pairs with risk above 60",
      "24h Volume: Higher volume = better liquidity and tighter spreads",
      "Last Signal: The most recent buy/sell signal generated for each pair",
      "Blacklist pairs you want to avoid by clicking the ban icon",
      "Sort by any column to find the best opportunities",
    ],
    tips: [
      "Focus on pairs with Trend Score > 70 AND Risk Score < 50 for the best risk/reward",
      "Higher volume pairs have better fill prices and lower slippage on Hyperliquid",
      "Blacklist pairs with very low volume or erratic price action",
    ],
    page: "pair-screener",
  },
  {
    number: 6,
    title: "Monitor Your Trades",
    description: "Track trade history, performance, and export data",
    details: [
      "Trade Log shows all completed trades with full details (entry, exit, P&L, duration)",
      "Use Filters to narrow down by pair, strategy, side (long/short), or outcome (win/loss)",
      "Summary stats show win rate, total P&L, average win/loss, and best/worst trades",
      "Export CSV button downloads filtered trade data for external analysis",
      "Green = win, Red = loss, Gray = breakeven",
      "Duration shows how long each trade was open (minutes, hours, or days)",
    ],
    tips: [
      "Review your Trade Log weekly to identify patterns in your winning and losing trades",
      "Export to CSV and analyze in Excel or Google Sheets for deeper insights",
      "Pay attention to which strategies have the best win rates on which pairs",
    ],
    page: "trade-log",
  },
  {
    number: 7,
    title: "Manage Risk",
    description: "Set risk limits and monitor exposure",
    details: [
      "Risk Monitor shows your current risk metrics and daily/weekly/monthly P&L",
      "Daily P&L chart shows your profit/loss for the last 30 days",
      "Circuit Breaker: Automatically stops all trading when daily losses exceed your limit",
      "Circuit Breaker has 3 levels: Warning (amber), Caution (red), Full Stop (halts everything)",
      "Pair Risk Allocation shows how your risk is distributed across trading pairs",
      "Sharpe Ratio: Risk-adjusted return. Above 2.0 is excellent, above 1.0 is good",
      "Max Drawdown: The largest peak-to-trough decline in your portfolio",
    ],
    tips: [
      "Set Daily Loss Limit to 3-7% of your portfolio for responsible risk management",
      "Never risk more than 1.5% on a single trade (configured in Settings)",
      "Monitor the Circuit Breaker level. If it hits Level 2, consider reviewing your strategies",
    ],
    warnings: [
      "The Circuit Breaker is your safety net. Do not set the daily loss limit too high",
      "If Circuit Breaker triggers frequently, reduce position sizes or disable losing strategies",
    ],
    page: "risk-monitor",
  },
];

const pageDescriptions = [
  {
    name: "Overview",
    icon: LayoutDashboard,
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/15",
    description: "Main dashboard with portfolio value, equity chart, live signals, active positions, and strategy status at a glance.",
  },
  {
    name: "Strategies",
    icon: Bot,
    color: "text-blue-400",
    bgColor: "bg-blue-500/15",
    description: "Enable/disable strategies, view performance metrics (win rate, P&L), and adjust parameters for each of the 4 trading strategies.",
  },
  {
    name: "AI Optimizer",
    icon: Sparkles,
    color: "text-purple-400",
    bgColor: "bg-purple-500/15",
    description: "Run Bayesian optimization (Optuna) to automatically find the best strategy parameters using historical backtesting data.",
  },
  {
    name: "Pair Screener",
    icon: Search,
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/15",
    description: "Browse and filter trading pairs by trend score, risk score, volume, and recent signals. Blacklist poor-performing pairs.",
  },
  {
    name: "Trade Log",
    icon: FileText,
    color: "text-amber-400",
    bgColor: "bg-amber-500/15",
    description: "Complete history of all trades with filters, summary statistics, and CSV export for external analysis.",
  },
  {
    name: "Risk Monitor",
    icon: Shield,
    color: "text-red-400",
    bgColor: "bg-red-500/15",
    description: "Real-time risk metrics, daily P&L chart, circuit breaker status, and pair-level risk allocation breakdown.",
  },
  {
    name: "Settings",
    icon: Settings,
    color: "text-zinc-400",
    bgColor: "bg-zinc-500/15",
    description: "Switch paper/live mode, configure risk limits, manage notifications, and view API connection status.",
  },
];

const quickFaq = [
  {
    q: "How do I switch from Paper to Live trading?",
    a: "Go to Settings and click the 'Live Trading' card. Make sure your wallet private key is set in bot/.env first. Always test thoroughly in Paper Mode before going live.",
  },
  {
    q: "The bot is running but I see no trades. Why?",
    a: "Strategies only trade when their specific conditions are met. Check that strategies are enabled, you have sufficient balance, and market conditions match the strategy requirements. On the 1h timeframe, signals can be infrequent.",
  },
  {
    q: "How do I stop the bot?",
    a: "Press Ctrl+C in the bot terminal window, or simply close the CMD window. Any open positions will remain on the exchange. Use the Cancel All feature in Settings to close all positions.",
  },
  {
    q: "What does the Circuit Breaker do?",
    a: "It automatically halts trading when daily losses exceed your configured limit (default 7% of portfolio). This prevents catastrophic losses during extreme market conditions. It has 3 escalation levels.",
  },
  {
    q: "Can I run this on a VPS for 24/7 trading?",
    a: "Yes. Install the bot on a Linux VPS (Ubuntu recommended) and run it with a process manager like systemd or pm2. This ensures it restarts automatically if the server reboots.",
  },
  {
    q: "How much ETH do I need to start?",
    a: "For paper trading, no ETH is needed. For live trading, Hyperliquid has no minimum deposit, but we recommend starting with at least 0.1 ETH to have meaningful position sizes.",
  },
];

export function Tutorial() {
  const [expandedStep, setExpandedStep] = useState<number | null>(1);
  const [expandedFaq, setExpandedFaq] = useState<number | null>(null);

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-zinc-50 flex items-center gap-3">
          <div className="rounded-lg bg-emerald-500/15 p-2">
            <BookOpen className="h-5 w-5 text-emerald-400" />
          </div>
          Getting Started Guide
        </h1>
        <p className="text-sm text-zinc-500 mt-1.5">
          Learn how to set up and use your ETH Trading Bot dashboard step by step
        </p>
      </div>

      {/* Quick Start Banner */}
      <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-5">
        <div className="flex items-start gap-3">
          <div className="rounded-lg bg-emerald-500/15 p-2 mt-0.5">
            <Rocket className="h-5 w-5 text-emerald-400" />
          </div>
          <div>
            <h2 className="text-sm font-semibold text-emerald-400 mb-1">
              Quick Start in 3 Steps
            </h2>
            <div className="flex flex-col sm:flex-row gap-2 sm:gap-4 mt-2">
              <div className="flex items-center gap-2">
                <div className="flex h-5 w-5 items-center justify-center rounded-full bg-emerald-500/20 text-[10px] font-bold text-emerald-400">
                  1
                </div>
                <span className="text-xs text-zinc-300">
                  <Wallet className="inline h-3 w-3 mr-1" />
                  Fund your Hyperliquid wallet
                </span>
              </div>
              <ChevronRight className="h-4 w-4 text-zinc-600 hidden sm:block" />
              <div className="flex items-center gap-2">
                <div className="flex h-5 w-5 items-center justify-center rounded-full bg-emerald-500/20 text-[10px] font-bold text-emerald-400">
                  2
                </div>
                <span className="text-xs text-zinc-300">
                  <Settings className="inline h-3 w-3 mr-1" />
                  Start in Paper Mode
                </span>
              </div>
              <ChevronRight className="h-4 w-4 text-zinc-600 hidden sm:block" />
              <div className="flex items-center gap-2">
                <div className="flex h-5 w-5 items-center justify-center rounded-full bg-emerald-500/20 text-[10px] font-bold text-emerald-400">
                  3
                </div>
                <span className="text-xs text-zinc-300">
                  <Eye className="inline h-3 w-3 mr-1" />
                  Monitor signals and let the bot trade
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Page Overview */}
      <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-5">
        <h2 className="text-base font-semibold text-zinc-100 mb-1">
          Dashboard Pages Overview
        </h2>
        <p className="text-xs text-zinc-500 mb-4">
          Your trading bot has 7 main pages, each serving a specific purpose
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
          {pageDescriptions.map((page) => (
            <div
              key={page.name}
              className="rounded-lg border border-zinc-800 bg-zinc-950/50 p-3 hover:border-zinc-700 transition-colors"
            >
              <div className="flex items-center gap-2 mb-2">
                <div className={cn("rounded-lg p-1.5", page.bgColor)}>
                  <page.icon className={cn("h-3.5 w-3.5", page.color)} />
                </div>
                <span className="text-xs font-semibold text-zinc-200">{page.name}</span>
              </div>
              <p className="text-[11px] text-zinc-500 leading-relaxed">
                {page.description}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Step-by-Step Tutorial */}
      <div>
        <h2 className="text-base font-semibold text-zinc-100 mb-4 flex items-center gap-2">
          <Zap className="h-4 w-4 text-amber-400" />
          Step-by-Step Tutorial
        </h2>
        <div className="space-y-3">
          {gettingStartedSteps.map((step) => (
            <div
              key={step.number}
              className="rounded-xl border border-zinc-800 bg-zinc-900 overflow-hidden"
            >
              {/* Step Header */}
              <button
                onClick={() =>
                  setExpandedStep(expandedStep === step.number ? null : step.number)
                }
                className="flex w-full items-center gap-4 p-4 text-left hover:bg-zinc-800/30 transition-colors"
              >
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-500/15 text-sm font-bold text-emerald-400">
                  {step.number}
                </div>
                <div className="flex-1 min-w-0">
                  <h3 className="text-sm font-semibold text-zinc-100">
                    {step.title}
                  </h3>
                  <p className="text-xs text-zinc-500 mt-0.5">
                    {step.description}
                  </p>
                </div>
                <ChevronRight
                  className={cn(
                    "h-4 w-4 shrink-0 text-zinc-600 transition-transform",
                    expandedStep === step.number && "rotate-90"
                  )}
                />
              </button>

              {/* Step Content */}
              {expandedStep === step.number && (
                <div className="border-t border-zinc-800 px-4 pb-4 pt-3">
                  {/* Details */}
                  <ul className="space-y-2 mb-4">
                    {step.details.map((detail, i) => (
                      <li key={i} className="flex items-start gap-2">
                        <CheckCircle2 className="h-3.5 w-3.5 text-emerald-400 shrink-0 mt-0.5" />
                        <span className="text-xs text-zinc-300 leading-relaxed">
                          {detail}
                        </span>
                      </li>
                    ))}
                  </ul>

                  {/* Tips */}
                  {step.tips && step.tips.length > 0 && (
                    <div className="rounded-lg bg-blue-500/5 border border-blue-500/15 p-3 mb-3">
                      <p className="text-[10px] font-semibold uppercase tracking-wider text-blue-400 mb-2">
                        Tips
                      </p>
                      <ul className="space-y-1.5">
                        {step.tips.map((tip, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="text-blue-400 text-xs shrink-0">+</span>
                            <span className="text-[11px] text-zinc-400 leading-relaxed">
                              {tip}
                            </span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Warnings */}
                  {step.warnings && step.warnings.length > 0 && (
                    <div className="rounded-lg bg-amber-500/5 border border-amber-500/15 p-3">
                      <p className="text-[10px] font-semibold uppercase tracking-wider text-amber-400 mb-2 flex items-center gap-1">
                        <AlertTriangle className="h-3 w-3" />
                        Warning
                      </p>
                      <ul className="space-y-1.5">
                        {step.warnings.map((warning, i) => (
                          <li key={i} className="flex items-start gap-2">
                            <span className="text-amber-400 text-xs shrink-0">!</span>
                            <span className="text-[11px] text-zinc-400 leading-relaxed">
                              {warning}
                            </span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* FAQ */}
      <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-5">
        <h2 className="text-base font-semibold text-zinc-100 mb-1">
          Frequently Asked Questions
        </h2>
        <p className="text-xs text-zinc-500 mb-4">
          Common questions about using the ETH Trading Bot
        </p>
        <div className="space-y-2">
          {quickFaq.map((faq, index) => (
            <div
              key={index}
              className="rounded-lg border border-zinc-800 overflow-hidden"
            >
              <button
                onClick={() =>
                  setExpandedFaq(expandedFaq === index ? null : index)
                }
                className="flex w-full items-center gap-3 p-3 text-left hover:bg-zinc-800/30 transition-colors"
              >
                <span className="text-xs font-semibold text-zinc-200 flex-1">
                  {faq.q}
                </span>
                <ChevronRight
                  className={cn(
                    "h-3.5 w-3.5 shrink-0 text-zinc-600 transition-transform",
                    expandedFaq === index && "rotate-90"
                  )}
                />
              </button>
              {expandedFaq === index && (
                <div className="border-t border-zinc-800 px-3 py-2.5">
                  <p className="text-xs text-zinc-400 leading-relaxed">
                    {faq.a}
                  </p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Bottom CTA */}
      <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-5 flex flex-col sm:flex-row items-start sm:items-center gap-4">
        <div className="flex-1">
          <h2 className="text-sm font-semibold text-zinc-100 mb-1">
            Ready to Start Trading?
          </h2>
          <p className="text-xs text-zinc-500">
            Head to the Overview page to see your bot in action, or visit Settings to
            configure your trading mode and risk parameters.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => window.location.hash = ""}
            className="flex items-center gap-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20 px-4 py-2 text-xs font-medium text-emerald-400 hover:bg-emerald-500/20 transition-colors"
          >
            <LayoutDashboard className="h-3.5 w-3.5" />
            Go to Overview
            <ArrowRight className="h-3 w-3" />
          </button>
          <button
            onClick={() => window.location.hash = ""}
            className="flex items-center gap-2 rounded-lg bg-zinc-800 px-4 py-2 text-xs font-medium text-zinc-300 hover:bg-zinc-700 transition-colors"
          >
            <Settings className="h-3.5 w-3.5" />
            Settings
          </button>
        </div>
      </div>
    </div>
  );
}
