"""
Base strategy class and Signal dataclass.

All trading strategies inherit from BaseStrategy and implement the
`calculate_signals` method.
"""

from __future__ import annotations

import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Optional

import pandas as pd


@dataclass
class Signal:
    """
    A trading signal generated by a strategy.

    Attributes:
        pair: Trading pair (e.g. "BTC").
        strategy: Name of the strategy that generated the signal.
        direction: "long" or "short".
        entry_price: Suggested entry price.
        stop_loss: Suggested stop-loss price.
        take_profit: Suggested take-profit price.
        confidence: Signal confidence score in [0, 1].
        timestamp: Unix timestamp in milliseconds when the signal was generated.
        metadata: Optional extra data (indicator values, etc.).
    """
    pair: str
    strategy: str
    direction: str          # "long" or "short"
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: float       # 0.0 to 1.0
    timestamp: int = field(default_factory=lambda: int(time.time() * 1000))
    metadata: dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Subclasses must implement:
      - calculate_signals(df) → list of Signal
      - name property

    And should override:
      - get_params() → dict of current parameter values
      - set_params(params) → update parameters
      - get_param_ranges() → dict of parameter ranges for optimization
    """

    def __init__(self, params: Optional[dict[str, Any]] = None) -> None:
        self._params: dict[str, Any] = {}
        if params:
            self.set_params(params)

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable strategy name."""
        ...

    @abstractmethod
    def calculate_signals(self, df: pd.DataFrame) -> list[Signal]:
        """
        Generate trading signals from an OHLCV DataFrame.

        The DataFrame must have columns: open, high, low, close, volume.

        Returns a list of Signal objects (may be empty).
        """
        ...

    def get_params(self) -> dict[str, Any]:
        """Return a copy of the current strategy parameters."""
        return dict(self._params)

    def set_params(self, params: dict[str, Any]) -> None:
        """Update strategy parameters from a dict."""
        valid = self.get_param_ranges()
        for key, value in params.items():
            if key in valid:
                lo, hi = valid[key]
                # Clamp to valid range
                clamped = max(lo, min(hi, value))
                self._params[key] = clamped
            else:
                self._params[key] = value

    def get_param_ranges(self) -> dict[str, tuple[float, float]]:
        """
        Return parameter search ranges for optimization.

        Override in subclasses. Keys match get_params keys.
        Values are (min, max) tuples.
        """
        return {}

    def required_candle_count(self) -> int:
        """Minimum number of candles needed for the strategy to work."""
        return 200

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(params={self._params})"
